# Generated by Django 2.0.4 on 2018-04-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelCPU', models.CharField(max_length=60)),
                ('patentCPU', models.CharField(max_length=50)),
                ('socket', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelGPU', models.CharField(max_length=60)),
                ('patentGPU', models.CharField(max_length=50)),
                ('busSupport', models.CharField(max_length=30)),
                ('memoryInterface', models.CharField(max_length=20)),
                ('maximumDigitalResolution', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherBoardName', models.CharField(max_length=60)),
                ('motherPatent', models.CharField(max_length=50)),
                ('USBRevision', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('CPURelated', models.ManyToManyField(to='product.Cpu')),
                ('GPURelated', models.ManyToManyField(to='product.Gpu')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='GPURelated',
            field=models.ManyToManyField(to='product.Gpu'),
        ),
    ]
