# Generated by Django 2.0.4 on 2018-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='TDP',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='baseFrequency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='maxFrequency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='maxTemperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='numberOfCores',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cpu',
            name='numberOfThreads',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gpu',
            name='baseCloack',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='maximumTemperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memoryCloack',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='recomendedSystemPower',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='busSpeed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='maxNumberOfSataPorts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='numberOfDIMMS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='numberOfDisplaysSupported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='numberOfUSBPorts',
            field=models.IntegerField(default=0),
        ),
    ]
