# Generated by Django 2.0.4 on 2018-04-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180426_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='modelCPU',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='modelGPU',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='motherBoardName',
            new_name='name',
        ),
    ]
