# Generated by Django 2.0.4 on 2018-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180426_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='socket',
        ),
        migrations.AddField(
            model_name='cpu',
            name='socketForCPU',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socketInMB',
            field=models.CharField(default='', max_length=80),
        ),
    ]
